[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
PORT = "3000"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PUBLIC_API_URL = "https://job-portal-ui-production.up.railway.app" 